name: Hello World Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, World! ยินดีด้วยครับคุณสร้าง Workflow แรกสำเร็จแล้ว"
