name : My First Workflow


on: 
    push:
        branches: 
            - gh-pages

job: 
    build:
       runs-on: ubuntu-latest
      steps:
            - name: Say Hello
              run: echo "Hello, World!"

