name: Deploy Static Web to GitHub Pages

on:
  push:
    branches:
      - main

# ตั้งค่า Permission ตามโจทย์ (contents, pages, id-token)
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: badin-042
        uses: actions/checkout@v4

     
      - name: actions/gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages 
